---
name: eliud_pkg_text_model
description: "eliud_pkg_text_model is a package to provide text-functionality to eliud platform.\
  \ \"text\" is the broad name for html, markdown and the likes. More info at https://eliud.io"
homepage: https://eliud.io
repository: https://github.com/eliudio/eliud_pkg_text
version: 1.0.0
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.12.2
  collection: ^1.17.2
  eliud_core:
    path: ../eliud_core
  eliud_core_helpers:
    path: ../eliud_core_helpers
  eliud_core_model:
    path: ../eliud_core_model
  eliud_pkg_medium:
    path: ../eliud_pkg_medium
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_inappwebview: ^5.8.0
  flutter_widget_from_html: ^0.14.6
  flutter_widget_from_html_core: ^0.14.6
  html: 0.15.4
  html_editor_enhanced: ^2.5.1
  meta: ^1.9.1
  universal_html: ^2.2.4
  pointer_interceptor: ^0.9.3+6
  url_launcher: ^6.2.1
  flutter:
    sdk: flutter
dev_dependencies:
  build_runner: ^2.4.6
  eliud_generator:
    path: ../eliud_generator
  lints: ^3.0.0
flutter:
  uses-material-design: true
platforms:
  android: null
  ios: null
  web: null
